// Route path sabitleri - Her coin için ayrı route
export const ROUTES = {
  HOME: '/',
  BTC: '/btc',
  ETH: '/eth',
  BNB: '/bnb',
  SOL: '/sol',
  XRP: '/xrp',
  DOGE: '/doge',
  ADA: '/ada',
  AVAX: '/avax',
  SHIB: '/shib',
  TRX: '/trx',
  DOT: '/dot',
  LINK: '/link',
  MATIC: '/matic',
  LTC: '/ltc',
  BCH: '/bch',
  NEAR: '/near',
  UNI: '/uni',
  PEPE: '/pepe',
  FET: '/fet',
  RNDR: '/rndr',
}

// Desteklenen tüm kripto paralar
export const KRIPTO_LISTESI = [
  { sembol: 'BTC', ad: 'Bitcoin', ikon: '₿', renk: '#f7931a', rota: ROUTES.BTC },
  { sembol: 'ETH', ad: 'Ethereum', ikon: 'Ξ', renk: '#627eea', rota: ROUTES.ETH },
  { sembol: 'BNB', ad: 'Binance Coin', ikon: '🔶', renk: '#f3ba2f', rota: ROUTES.BNB },
  { sembol: 'SOL', ad: 'Solana', ikon: '◎', renk: '#14f195', rota: ROUTES.SOL },
  { sembol: 'XRP', ad: 'Ripple', ikon: '✕', renk: '#23292f', rota: ROUTES.XRP },
  { sembol: 'DOGE', ad: 'Dogecoin', ikon: '🐕', renk: '#c2a633', rota: ROUTES.DOGE },
  { sembol: 'ADA', ad: 'Cardano', ikon: '🔵', renk: '#0033ad', rota: ROUTES.ADA },
  { sembol: 'AVAX', ad: 'Avalanche', ikon: '🔺', renk: '#e84142', rota: ROUTES.AVAX },
  { sembol: 'SHIB', ad: 'Shiba Inu', ikon: '🐶', renk: '#ffa409', rota: ROUTES.SHIB },
  { sembol: 'TRX', ad: 'Tron', ikon: '⚡', renk: '#ff0013', rota: ROUTES.TRX },
  { sembol: 'DOT', ad: 'Polkadot', ikon: '●', renk: '#e6007a', rota: ROUTES.DOT },
  { sembol: 'LINK', ad: 'Chainlink', ikon: '⬡', renk: '#2a5ada', rota: ROUTES.LINK },
  { sembol: 'MATIC', ad: 'Polygon', ikon: '⬟', renk: '#8247e5', rota: ROUTES.MATIC },
  { sembol: 'LTC', ad: 'Litecoin', ikon: 'Ł', renk: '#bfbbbb', rota: ROUTES.LTC },
  { sembol: 'BCH', ad: 'Bitcoin Cash', ikon: '₿', renk: '#8dc351', rota: ROUTES.BCH },
  { sembol: 'NEAR', ad: 'Near Protocol', ikon: 'Ⓝ', renk: '#00c1de', rota: ROUTES.NEAR },
  { sembol: 'UNI', ad: 'Uniswap', ikon: '🦄', renk: '#ff007a', rota: ROUTES.UNI },
  { sembol: 'PEPE', ad: 'Pepe', ikon: '🐸', renk: '#4a9c4e', rota: ROUTES.PEPE },
  { sembol: 'FET', ad: 'Fetch.ai', ikon: '🤖', renk: '#1d2951', rota: ROUTES.FET },
  { sembol: 'RNDR', ad: 'Render', ikon: '🎨', renk: '#c9b3f5', rota: ROUTES.RNDR },
]
